SPDX Defects Team meeting - 9th March 2022
spdx/meetings pull request #137
Opened 2022-03-09 21:53 UTC by rnjudge

Signed-off-by: Rose Judge <rjudge@vmware.com>

2022-03-09 22:41 UTC, rjb4standards requested changes

2022-03-09 22:41 UTC, rjb4standards commented on defects/2022-03-09.md
> +* Thomas TODO: Add a 3rd option to SPDX 2.3 documentation
There was a suggestion to set a goal to reach consensus on one of the 3 options at our next meeting in order to meet the NTIA minimum implementation timeline, currently scheduled for August 2022.

2022-03-11 00:46 UTC, jeff-schutt requested changes

2022-03-11 00:46 UTC, jeff-schutt commented on defects/2022-03-09.md
> +* Dick: One concern related to NTIA support for US EA. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely ne
```suggestion
* Dick: One concern related to NTIA support for US EO. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely need to be re-coded to do this.
```

2022-03-11 00:46 UTC, jeff-schutt commented on defects/2022-03-09.md
> +    * Jeff: While SPDX lists packages as a component, the SPDX document itself recognizes a component which also has its own identifier and document namespace?
```suggestion
    * Jeff: SPDX lists packages as components and each package has a unique identifier in the SPDX document, which meets the NTIA 'other unique identifiers' requirement. Kate is highlighting that the software that SPDX document references is recognized as a component, and so the SPDX document has its own unique identifier by means of the document namespace, also meeting the NTIA requirement.
```

2022-03-11 22:19 UTC, rnjudge commented on defects/2022-03-09.md
> +* Dick: One concern related to NTIA support for US EA. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely ne
Good catch, Jeff! Fixed.

2022-03-11 22:21 UTC, rnjudge commented on defects/2022-03-09.md
> +    * Jeff: While SPDX lists packages as a component, the SPDX document itself recognizes a component which also has its own identifier and document namespace?
Thanks again, Jeff. I updated my PR to reflect your suggestion.

2022-03-16 19:06 UTC, merged

2022-10-11 07:28 UTC, rjb4standards commented
good catch, Jeff. thanx

Sent from my iPhone

> On Mar 10, 2022, at 7:47 PM, Jeff Schutt ***@***.***> wrote:
> 
> ﻿
> @jeff-schutt requested changes on this pull request.
> 
> In defects/2022-03-09.md:
> 
> > +### General
> +* No objections to last weeks minutes. Will merge after the call.
> +
> +###  Changing SPDX 2.x to enable SBOM without licensing fields to solely support security use cases
> +* 2.2 has several mandatory fields related to licensing. SPDX call had brief discussion two weeks ago about whether SPDX can *only* communicate security information (free of licensing info, which SPDX was created to communicate). 
> +* We are working on 2.3 which can communicate security info - should we change the spec to make some of the license fields optional (i.e. declared license, copyright field, etc). If you are communicating security information and don't care about lisencing, why should we require it? Note that these fields can be ommitted by using `NOASSERTION` or `NONE`.
> +* We need the legal team to review, as well as the general call.
> +* Can we use profiles in 3.0 to address this? Yes, profiles will fix this but what should we do for 2.3?
> +* If we require licensing infromation can lead to [size] inflated SBOMs with lots of NONEs and NOASSERTIONs.
> +* Dick agrees a lot of the licensing material is extraneous but he can go either way right now.
> +* Jeff: if we are adapting 2.3 to disclose security information about components then we should be able to omit licensing information (Dick agrees).
> +* Are we getting complaints/requests for this? 
> +* We are waiting for someone to open a PR in the repo for this? Yes. Fields that are related to licensing and have a NOASSERTION option that are currently mandatory should be moved to optional. Rose volunteers to help open this PR.
> +  * ConcludedLicense, All License information from package (licenses from file, etc), DeclaredLicense, CopyrightText for packages, files and snippets.
> +  * https://spdx.dev/wp-content/uploads/sites/41/2020/04/spdx_onepager.pdf
> +* Dick: One concern related to NTIA support for US EA. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely need to be re-coded to do this.
> ⬇️ Suggested change
> -* Dick: One concern related to NTIA support for US EA. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely need to be re-coded to do this.
> +* Dick: One concern related to NTIA support for US EO. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely need to be re-coded to do this.
> In defects/2022-03-09.md:
> 
> > +* We need the legal team to review, as well as the general call.
> +* Can we use profiles in 3.0 to address this? Yes, profiles will fix this but what should we do for 2.3?
> +* If we require licensing infromation can lead to [size] inflated SBOMs with lots of NONEs and NOASSERTIONs.
> +* Dick agrees a lot of the licensing material is extraneous but he can go either way right now.
> +* Jeff: if we are adapting 2.3 to disclose security information about components then we should be able to omit licensing information (Dick agrees).
> +* Are we getting complaints/requests for this? 
> +* We are waiting for someone to open a PR in the repo for this? Yes. Fields that are related to licensing and have a NOASSERTION option that are currently mandatory should be moved to optional. Rose volunteers to help open this PR.
> +  * ConcludedLicense, All License information from package (licenses from file, etc), DeclaredLicense, CopyrightText for packages, files and snippets.
> +  * https://spdx.dev/wp-content/uploads/sites/41/2020/04/spdx_onepager.pdf
> +* Dick: One concern related to NTIA support for US EA. If we make this change, is it going to create any delay in getting 2.3 out the door before the August deadline? Validation checks will likely need to be re-coded to do this.
> +  * Validation tooling will need to be adjusted to not flag if it's missing.
> +  * Q: Anyone from tooling that could tell us how big of a change this would be? A: Gary ONeall 
> +* Kate shares comparison of NTIA comparison to SPDX fields: (https://docs.google.com/document/d/1fkw_RwdTPH2XvrlLQFanYr_A0JFF6y9KB5HncrcZFYM/edit)
> +    * 7.2 Unique identifier NTIA minimum columnn: part 1 you have to have a namespace part 2 is you have to have something relative to that namespace
> +    * Kate: NTIA wording for component: unit of software defined by the supplier (package or snippet).
> +    * Jeff: While SPDX lists packages as a component, the SPDX document itself recognizes a component which also has its own identifier and document namespace? 
> ⬇️ Suggested change
> -    * Jeff: While SPDX lists packages as a component, the SPDX document itself recognizes a component which also has its own identifier and document namespace? 
> +    * Jeff: SPDX lists packages as components and each package has a unique identifier in the SPDX document, which meets the NTIA 'other unique identifiers' requirement. Kate is highlighting that the software that SPDX document references is recognized as a component, and so the SPDX document has its own unique identifier by means of the document namespace, also meeting the NTIA requirement.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.