Add SPDX Implementers Team Meeting - 22 Mar, 2023
spdx/meetings pull request #308
Opened 2023-03-23 18:20 UTC by rnjudge

2023-03-23 20:37 UTC, goneall requested changes
Sorry about the confusion on the CDX/tools - one correction request

2023-03-23 20:37 UTC, goneall commented on implementers/2023-03-22.md
> +* There is a java tool that converts SPDX to CDX: https://github.com/spdx/cdx2spdx
Actually, this converts CDX to SPDX - the conversion from SPDX to CDX has been integrated into the C# CycloneDX CLI: https://github.com/CycloneDX/cyclonedx-cli - suggest replacing the above with "There is a C# tool that converts SPDX to CDX: https://github.com/CycloneDX/cyclonedx-cli

2023-03-23 21:36 UTC, rnjudge commented on implementers/2023-03-22.md
> +* There is a java tool that converts SPDX to CDX: https://github.com/spdx/cdx2spdx
Thanks @goneall - Can you take a look at the changes I pushed?

2023-03-24 03:33 UTC, goneall approved these changes
Thanks @rnjudge - looks good

2023-05-23 22:33 UTC, merged