Tech Team meetings 06.16 and 06.20
spdx/meetings pull request #352
Opened 2023-06-26 13:51 UTC by robcraig-LF

adds two meeting SPDX Tech 06.16 and 06.20

2023-06-26 19:05 UTC, goneall requested changes
One requested change

2023-06-26 19:05 UTC, goneall commented on tech/2023-06-20.md
> +  - Objections? None expressed
Suggest adding: `DECISION: use relationships for declaredLicense and concludedLicense` and add to decisions.md file

2023-07-13 18:31 UTC, robcraig-LF commented on tech/2023-06-20.md
> +  - Objections? None expressed
added to line 38. Will at to Decision file on separate PR to avoid conflicts.

2023-07-13 18:55 UTC, goneall approved these changes
LGTM

2023-07-13 18:55 UTC, merged