Create 2023-07-06
spdx/meetings pull request #356
Opened 2023-07-06 16:38 UTC by robcraig-LF

Adds meeting agenda/minutes SPDX Serialization Team Meeting 2023-07-06

2023-07-06 18:28 UTC, goneall requested changes
Suggest adding the comments only if @zvr agrees

2023-07-06 18:28 UTC, goneall commented on serialisation/2023-07-06
> +  - other formats, possibly including a very simple printf-generated
I would like to add the following which was discussed in the meeting.

@zvr - let me know if you agree:

- Next meeting, we'll focus on a decision of the JSON-LD format can be a more general JSON format or if we need a second JSON format
- If we decide we need a second format, we will document the issues with the JSON-LD
- If we decide we need a second format, we will review David's proposal and decide if it meets the needs for a second JSON format or document the issues preventing it from being accepted

2023-07-07 15:00 UTC, zvr commented on serialisation/2023-07-06
> +  - other formats, possibly including a very simple printf-generated
Completly agree -- I did not type all this, but it was definitely in our call

2023-07-07 16:50 UTC, goneall commented
@robcraig-LF - I went ahead and added the additional bullets to the commit.

I also noticed that the filename was missing the .md file extension.

I'll create a commit to rename the file - you may want to check the other files to make sure they end in .md.

2023-07-07 16:52 UTC, goneall approved these changes

2023-07-30 00:26 UTC, merged