Create CONTRIBUTING.md
spdx/meetings pull request #373
Opened 2023-07-17 21:38 UTC by goneall

2023-07-17 21:56 UTC, zvr requested changes

2023-07-17 21:56 UTC, zvr commented on CONTRIBUTING.md
> +One week should be allowed for review.
Actually, I'd propose something different:

> Sufficient time should be allowed for review before merging.
> It is suggested that there is at least one review from an attendee of the meeting, but even if no reviews, it should be merged before the next meeting.

I believe that the monthly meeting minutes may take 3 weeks before merging without issue, but weekly meetings notes should be merged more frequently. Or do you think it's too much of a load?

2023-07-18 00:21 UTC, goneall commented on CONTRIBUTING.md
> +One week should be allowed for review.
I agree with the suggestion - updated the PR

2023-07-18 06:34 UTC, zvr approved these changes

2023-07-18 19:33 UTC, jlovejoy commented
made one minor suggestion, but otherwise LGTM. Thanks @goneall !

2023-07-25 19:07 UTC, swinslow approved these changes

2023-07-25 19:08 UTC, kestewart approved these changes

2023-07-25 19:08 UTC, merged