Create Namespace Discussion 2023-09-18.md
spdx/meetings pull request #481
Opened 2023-09-18 18:45 UTC by robcraig-LF

Adds meeting minutes and agenda from Namespace Discussion 2023-09-18

2023-09-18 19:33 UTC, goneall requested changes
Thanks @robcraig-LF for posting this - if you could make the 2 minor corrections.

2023-09-18 19:33 UTC, goneall commented on tech/Namespace Discussion 2023-09-18.md
> +* Bob
```suggestion
* Bob Martin
```

2023-09-18 19:33 UTC, goneall commented on tech/Namespace Discussion 2023-09-18.md
> +# Minutes
```suggestion
```

2023-09-18 19:42 UTC, robcraig-LF commented
Updates made as requested

2023-09-19 00:46 UTC, goneall commented
@robcraig-LF - Thanks for the update.  I don't think you intended to close the pull request (perhaps you intended to close the comment issue)?  

I'll re-open and merge.

2023-09-19 00:46 UTC, goneall approved these changes
LGTM

2023-09-19 00:46 UTC, merged