Create SPDX AI Team Minutes 2023-05-17.md
spdx/meetings pull request #530
Opened 2023-10-13 13:07 UTC by robcraig-LF

Adds meeting minutes and agenda SPDX AI Team Minutes 2023-05-17

2024-01-24 11:33 UTC, bennetkl requested changes
Remove space with Jay White's name

2024-02-28 10:02 UTC, bact requested changes

2024-03-19 18:04 UTC, bennetkl commented
Merge

2024-05-15 10:37 UTC, bact commented on ai/SPDX AI Team Minutes 2023-05-17.md
> +*j ay white
`*j ay white` --> `* Jay White`

2024-05-15 11:34 UTC, closed without merging